### ISSUE TITLE
新增功能

### ISSUE THREAD

**Issue by l455202325** [ithere/douyin-meinv-miniapp#1]
1.新增分页功能，你的是（1-10）随机页码，只有小程序完全退出才能刷新新的页面，大部分人还不熟悉怎么完全退出小程序，所以每次进来都是一样的；
2.增加在线直接播放功能

**Comment by ithere** [comment]
> 1.新增分页功能，你的是（1-10）随机页码，只有小程序完全退出才能刷新新的页面，大部分人还不熟悉怎么完全退出小程序，所以每次进来都是一样的；
> 2.增加在线直接播放功能

感谢朋友的分享 已merge。其实本来是有直接观看的功能的，但是一页全部加载的时候会非常非常吃内存，超级占用运存还会造成卡死，有明显卡顿 假死状态 所以我才去掉的。

**Comment by l455202325** [comment]
不要在列表页直接播放，点击后在播放就可以了
